### ISSUE TITLE
Where in .travis.yml is yaspeller-ci called from?

### ISSUE THREAD

**Issue by luzpaz** [ai/yaspeller-ci#2]
I'm trying to understand how yaspeller is installed and triggered within the .travis.yml so that it tests each PR submitted to a project's repository...? Any help would be appreciated!

**Comment by amureki** [comment]
Hi @luzpaz !

For an example of configuration you can check my public repository: https://github.com/amureki/django_faq

As you can see, in travis there is configured only repo language as node_js.
And this automagically checks `package.json` file for scripts.
There you can see script part configured like this:
```
  "scripts": {
    "spellcheck": "yaspeller-ci",
    "test": "npm run spellcheck *.md"
  }
```

So, travis runs test, which itself runs spellcheck script.

You can directly call yaspeller from .travis file also.

**Comment by ai** [comment]
Yeap. You should put Yaspeller CI too your tests. In most of cases you don't need to change `.travis.yml`.

**Comment by luzpaz** [comment]
thanks!
